export const he = {
  appName: "המשחק של סבתא נמרודי",
  newGame: "משחק חדש",
  continueGame: "המשך משחק",
  settings: "הגדרות",
  bestResult: "התוצאה הטובה ביותר",
  totalGames: "משחקים ששוחקו",
  lostGames: "משחקים שהפסדתם",
  currentStatus: "מצב נוכחי",
  pilesLeft: "ערימות",
  deck: "חפיסה",
  revealCard: "חשוף קלף",
  undo: "בטל מהלך",
  restart: "התחל מחדש",
  home: "חזרה למסך הבית",
  menu: "תפריט",
  noSavedGame: "אין משחק שמור כרגע",
  noMovesHint: "אין כרגע חיבור אפשרי. אפשר לחשוף קלף נוסף.",
  canMoveNear: "אפשר להניח על הערימה הקודמת.",
  canMoveFar: "אפשר להניח על הערימה שלפני שלוש עמדות.",
  canMoveBoth: "יש שתי אפשרויות חיבור פתוחות.",
  finished: "הסיבוב הסתיים",
  won: "ניצחת",
  lost: "הפסדת",
  bravo: "כל הכבוד",
  tryAgain: "נסו שוב בעדינות",
  replay: "שחקו שוב",
  shareResult: "שתפו בוואטסאפ",
  sound: "צלילים",
  music: "מוזיקה",
  vibration: "רטט",
  reduceMotion: "הפחתת תנועה",
  clueMode: "מצב רמזים",
  cardTheme: "סגנון קלפים",
  howToPlay: "איך משחקים",
  howLine1: "חושפים קלף אחד בכל פעם. כל קלף יוצר ערימה חדשה בקצה השורה.",
  howLine2: "אפשר להניח את הערימה הימנית ביותר על הערימה שלפניה אם יש התאמה בדרגה או בסוג.",
  howLine3: "אפשר גם להניח אותה על הערימה שנמצאת שלוש עמדות אחורה אם יש התאמה.",
  howLine4: "המטרה היא לסיים עם כמה שפחות ערימות. ערימה אחת היא תוצאה מושלמת.",
  classicTheme: "קלאסי",
  ivoryTheme: "שנהב",
  resume: "חזרה למשחק",
  revealMore: "חשפו עוד קלפים",
  remainingDeck: "קלפים שנותרו",
  tapTarget: "לחצו על אחת הערימות המודגשות כדי לחבר.",
  invalidMove: "כאן אי אפשר לחבר",
  noUndo: "אין מה לבטל כרגע",
  statusReady: "אפשר להתחיל לחשוף קלפים",
  statusFinished: "החפיסה נגמרה ואין עוד מהלכים",
  titleSubtitle: "סוליטר אקורדיון בניחוח ביתי",
  statsTitle: "זיכרונות מהשולחן",
  selectRightmost: "בחרו ערימה",
  chooseDestination: "בחרו יעד",
  fullPileView: "כל הקלפים הפתוחים נשארים גלויים לאורך כל הסיבוב",
  customBackComingSoon: "תמונת סבתא תוכל להופיע כאן בגב הקלפים",
  moveAnimation: "הערימה תחליק אל היעד כדי שיהיה ברור מה קרה",
  exitGame: "יציאה",
  rotateLandscape: "כדי לשחק בנוחות, סובבו את המכשיר לרוחב",
  boardTitle: "השולחן",
  deckAction: "חשיפת קלף חדש",
  selectionIdle: "בחרו כל ערימה כדי לראות לאן אפשר להזיז אותה.",
  selectionActive: "ערימת היעד האפשריות מוארות על השולחן.",
  quickHelp: "איך משחקים",
  quickSettings: "הגדרות",
  pause: "השהיה",
  resumeGame: "חזרה למשחק",
  pauseCover: "אבדאלאק!!",
  close: "סגור",
  timerLabel: "זמן למהלך",
  timerExpired: "הזמן נגמר",
};
